package login;


import admin.Admin_Fitur;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import karyawan.start_Home;
import koneksiDB.koneksi;

/**
 *
 * @author Daffa Aditya Rejasa Ruswanto
 */

public class Login_RFID_KTP extends javax.swing.JFrame {

    /**
     * Creates new form ScnCode
     */
    public Login_RFID_KTP() {
        initComponents();
        this.setTitle("LOGIN KARTU");
        
       
        
    }
    
    public void confirm(){
        int jawab = JOptionPane.showConfirmDialog(this, "Ingin menggunakan Login Manual?");
    
    // 0 : yes
    // 1 : no
    // 2 : cancel
    
    switch(jawab){
        case JOptionPane.YES_OPTION: 
            this.setVisible(false);
            new LoginApp().setVisible(true);
            break;
        case JOptionPane.NO_OPTION:
            JOptionPane.showMessageDialog(this, "Silakan Coba Lagi!");
            p.setText("");
            break;
        case JOptionPane.CANCEL_OPTION:
            p.setText("");
            
    }
    
    }
    public void BatasWajarInput(KeyEvent a){
        if(p.getText().trim().length()>=11){
            a.consume();
            confirm();
            p.setText("");
        }
    }
    
    public void loginKartu(String key){
        String sql = "SELECT `login`.`username`,`login`.`password`,`karyawan`.`nama_krywn`,`karyawan`.`type`,`karyawan`.`loginKartu` FROM `login` JOIN `karyawan` ON `karyawan`.`idkrywn` = `login`.`idkrywn`;";
        try{
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.PreparedStatement stm = conn.prepareStatement(sql);
            java.sql.ResultSet rs= stm.executeQuery();
            //0308356356
            
            while(rs.next()){
                if(key.toString().equals(rs.getString(5))){
                    if(key.toString().equals("")){
                        JOptionPane.showMessageDialog(this, "LOGIN GAGAL.");
                        break;
                    } else {
                                 
                                 this.setVisible(false);
//                               new tes12().setVisible(true);
                                 String type = rs.getString(4);
                                 
                                 if(type.equals("Karyawan")|| type.equals("karyawan")){
                                     
                                     new start_Home(rs.getString(1)).setVisible(true);
                                     
                                     
                                     
                                 } else if (type.equals("Bos")){
                                     
                                     new Admin_Fitur(rs.getString(1)).setVisible(true);
                                     
                                     
                                 }
                                 
                    }
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        p = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LOGKartu_2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        userr.setText("jLabel2");
        getContentPane().add(userr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        p.setBorder(null);
        p.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        p.setOpaque(false);
        p.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pKeyTyped(evt);
            }
        });
        getContentPane().add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 100, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pKeyReleased
        // TODO add your handling code here:
        String key = p.getText().trim();
        if(key !=""){
            loginKartu(key);
        }
    }//GEN-LAST:event_pKeyReleased

    private void pKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pKeyTyped
        // TODO add your handling code here:
        BatasWajarInput(evt);
        
    }//GEN-LAST:event_pKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
              try {
            UIManager.setLookAndFeel( UIManager.getCrossPlatformLookAndFeelClassName() );
         } catch (Exception e) {
            e.printStackTrace();
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_RFID_KTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_RFID_KTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_RFID_KTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_RFID_KTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_RFID_KTP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField p;
    public static final javax.swing.JLabel userr = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
}
