/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package karyawan;

import Setting.Setting_BackUpDb;
import java.sql.Connection;
import javax.swing.UIManager;
import koneksiDB.koneksi;
/**
 *
 * @author Windows 10
 */
public class Karyawan_LaporanSwitch extends javax.swing.JFrame {

    /**
     * Creates new form Karyawan_LaporanSwitch
     */
    public Karyawan_LaporanSwitch(String nama) {
        initComponents();
        this.setTitle("MENU LAPORAN");
        SetNama(nama);
        textID();
    }
    public void SetNama(String user){
        userr.setText(user);
    }
    public void textID(){
        try{
            String query = "SELECT `login`.`username`,`login`.`password`,"
                    + "`karyawan`.`nama_krywn`,`karyawan`.`type` FROM "
                    + "`login` JOIN `karyawan` ON `karyawan`.`idkrywn` = `login`.`idkrywn` WHERE username = '"+userr.getText()+"'";
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.Statement statementObj = conn.createStatement();
            java.sql.ResultSet rs = statementObj.executeQuery(query);
            
            while(rs.next()){
                
                if(rs.getString(4).equals("Karyawan")||rs.getString(4).equals("karyawan")){
                    adminId.setVisible(false);
                    karyawanId.setVisible(true);
                    
                } else  if(rs.getString(4).equals("Bos")){
                    adminId.setVisible(true);
                    karyawanId.setVisible(false);
                }
            
            }
        }catch(Exception e){
            e.getMessage();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_home = new javax.swing.JButton();
        btn_Suplier = new javax.swing.JButton();
        btn_trans = new javax.swing.JButton();
        btn_report = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn_report1 = new javax.swing.JButton();
        adminId = new javax.swing.JLabel();
        karyawanId = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home.setBackground(new java.awt.Color(51, 51, 255));
        btn_home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-home-24.png"))); // NOI18N
        btn_home.setText("HOME");
        btn_home.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        btn_home.setContentAreaFilled(false);
        btn_home.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 170, 40));

        btn_Suplier.setBackground(new java.awt.Color(51, 51, 255));
        btn_Suplier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Suplier.setForeground(new java.awt.Color(255, 255, 255));
        btn_Suplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-supplier-24.png"))); // NOI18N
        btn_Suplier.setText("SUPLIER");
        btn_Suplier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        btn_Suplier.setContentAreaFilled(false);
        btn_Suplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuplierActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Suplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 170, 40));

        btn_trans.setBackground(new java.awt.Color(51, 51, 255));
        btn_trans.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_trans.setForeground(new java.awt.Color(255, 255, 255));
        btn_trans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-cashier-24.png"))); // NOI18N
        btn_trans.setText("TRANSAKSI");
        btn_trans.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        btn_trans.setContentAreaFilled(false);
        btn_trans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transActionPerformed(evt);
            }
        });
        getContentPane().add(btn_trans, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 170, 40));

        btn_report.setBackground(new java.awt.Color(51, 51, 255));
        btn_report.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_report.setForeground(new java.awt.Color(255, 255, 255));
        btn_report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-report-24.png"))); // NOI18N
        btn_report.setText("REPORT");
        btn_report.setBorder(null);
        btn_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportActionPerformed(evt);
            }
        });
        getContentPane().add(btn_report, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 170, 40));

        jButton2.setBackground(new java.awt.Color(255, 101, 132));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("LAPORAN HARIAN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 390, 50));

        jButton1.setBackground(new java.awt.Color(255, 101, 132));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LAPORAN BULAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 390, 50));

        btn_report1.setBackground(new java.awt.Color(51, 51, 255));
        btn_report1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_report1.setForeground(new java.awt.Color(255, 255, 255));
        btn_report1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-setting-24.png"))); // NOI18N
        btn_report1.setText("SETTING");
        btn_report1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        btn_report1.setContentAreaFilled(false);
        btn_report1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_report1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_report1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 170, 40));

        adminId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        adminId.setForeground(new java.awt.Color(255, 255, 255));
        adminId.setText("ID Admin :");
        getContentPane().add(adminId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 90, 30));

        userr.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userr.setForeground(new java.awt.Color(255, 255, 255));
        userr.setText("jLabel1");
        getContentPane().add(userr, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, -1, 30));

        karyawanId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        karyawanId.setForeground(new java.awt.Color(255, 255, 255));
        karyawanId.setText("ID Karyawan :");
        getContentPane().add(karyawanId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 110, 30));

        jPanel1.setBackground(new java.awt.Color(255, 101, 132));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/EfashionFrame.png"))); // NOI18N
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 210, 110));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/DataLaporan.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new start_Home(userr.getText()).setVisible(true);
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_SuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuplierActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Karyawan_ListDataSuplier(userr.getText()).setVisible(true);
    }//GEN-LAST:event_btn_SuplierActionPerformed

    private void btn_transActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Karyawan_Transaksi(userr.getText()).setVisible(true);
    }//GEN-LAST:event_btn_transActionPerformed

    private void btn_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_reportActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Karyawan_LaporanHari(userr.getText()).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Karyawan_LaporanBulan(userr.getText()).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_report1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_report1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Setting_BackUpDb(userr.getText()).setVisible(true);
    }//GEN-LAST:event_btn_report1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
              try {
            UIManager.setLookAndFeel( UIManager.getCrossPlatformLookAndFeelClassName() );
         } catch (Exception e) {
            e.printStackTrace();
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Karyawan_LaporanSwitch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Karyawan_LaporanSwitch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Karyawan_LaporanSwitch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Karyawan_LaporanSwitch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Karyawan_LaporanSwitch(userr.getText()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminId;
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_Suplier;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_report;
    private javax.swing.JButton btn_report1;
    private javax.swing.JButton btn_trans;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel karyawanId;
    public static final javax.swing.JLabel userr = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
}
