
package karyawan;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import koneksiDB.koneksi;

/**
 *
 * @author Daffa Aditya Rejasa Ruswanto
 */
public class Karyawan_Profile extends javax.swing.JFrame {

    String getSelectedImage = "";
    
    public Karyawan_Profile(String nama) {
        initComponents();
         this.setTitle("PROFILE");
        blankPic.setVisible(false);
        SetNama(nama);
        tampilane();
        
        
    }
    public void SetNama(String user){
        txUser.setText(user);
    }
    
    public static String escapePath(String path) {
        return path.replace("\\", "\\\\");
    }
    public void gantiProfile(){
        String gbr = escapePath(getSelectedImage.toString());
        String gantiPic = "UPDATE karyawan,login SET prof = '"+ gbr+"' WHERE username = '"+txUser.getText()+"' AND karyawan.idkrywn = login.idkrywn";
        System.out.println(gantiPic);
        
        try{
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.PreparedStatement stm = conn.prepareStatement(gantiPic);
            stm.execute();
            JOptionPane.showMessageDialog(this, "photo Berhasil ditambahkan");
            tampilane();
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        
        }
    
    }
      public void tampilane(){
       String sqlw2 = "SELECT * FROM login JOIN `karyawan` ON `karyawan`.`idkrywn` = `login`.`idkrywn` WHERE username = '"+txUser.getText()+"'";
          System.out.println(sqlw2);
       try{
           java.sql.Connection conn = (Connection) koneksi.configDB();
           java.sql.PreparedStatement stm = conn.prepareStatement(sqlw2);
           java.sql.ResultSet r = stm.executeQuery();
           if(r.next()){
               
               String pegawai = r.getString(5);
               String jabatan = r.getString(9);
               String alamat = r.getString(6);
               String nomerTlp = r.getString(7);
               String halu = r.getString(10);
            if(halu.isEmpty()){
                
                setNamaPegawai.setText(pegawai);
                SetJabaran.setText(jabatan);
                userAlamat.setText(alamat);
                telphone.setText(nomerTlp);
                blankPic.setVisible(true);
                profilee.setVisible(false);
            } else {
                setNamaPegawai.setText(pegawai);
                SetJabaran.setText(jabatan);
                userAlamat.setText(alamat);
                telphone.setText(nomerTlp);
                
                ImageIcon imIco = new ImageIcon(halu);
                Image imFit = imIco.getImage();
                Image imgFit = imFit.getScaledInstance(profilee.getWidth(), profilee.getHeight(), Image.SCALE_SMOOTH);
                profilee.setIcon(new ImageIcon(imgFit));
                profilee.setVisible(true);
                blankPic.setVisible(false);
            }
           
           }
           
       }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
       }
   
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        frameAjaib = new javax.swing.JLabel();
        profilee = new javax.swing.JLabel();
        blankPic = new javax.swing.JLabel();
        setNamaPegawai = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        telphone = new javax.swing.JTextField();
        SetJabaran = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        userAlamat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        frameAjaib.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/FrameKuProfile_1.png"))); // NOI18N
        jPanel1.add(frameAjaib, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel1.add(profilee, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 108, 107));

        blankPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/picBlank.png"))); // NOI18N
        jPanel1.add(blankPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        setNamaPegawai.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        setNamaPegawai.setText("ANGEL ROSIANSTI");
        jPanel1.add(setNamaPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 370, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("PROFILE PEGAWAI :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jLabel3.setText("No Telephone");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 80, -1));

        telphone.setEditable(false);
        telphone.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(telphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 220, 40));

        SetJabaran.setText("Karyawan");
        jPanel1.add(SetJabaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        txUser.setEditable(false);
        txUser.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(txUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 110, 40));

        jLabel5.setText("Id User  :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 50, -1));

        userAlamat.setEditable(false);
        userAlamat.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(userAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 220, 40));

        jLabel6.setText("Alamat :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 50, -1));

        jButton2.setBackground(new java.awt.Color(255, 101, 132));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-back-24.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 50, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("PiILIH FOTO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 110, 40));

        jButton3.setBackground(new java.awt.Color(102, 204, 255));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-save-24.png"))); // NOI18N
        jButton3.setText("SIMPAN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 150, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 320));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("4 Extensions Supported","jpg","png","jpeg","gif");
        fileChooser.setFileFilter(filter);
        int selected = fileChooser.showOpenDialog(null);
        if(selected == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            getSelectedImage = file.getAbsolutePath();
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        gantiProfile();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Karyawan_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Karyawan_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Karyawan_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Karyawan_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Karyawan_Profile(txUser.getText()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SetJabaran;
    private javax.swing.JLabel blankPic;
    private javax.swing.JLabel frameAjaib;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel profilee;
    private javax.swing.JLabel setNamaPegawai;
    private javax.swing.JTextField telphone;
    public static final javax.swing.JTextField txUser = new javax.swing.JTextField();
    private javax.swing.JTextField userAlamat;
    // End of variables declaration//GEN-END:variables
}
