/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import interface_pkgefashion.UpdateKaryawan;
import interface_pkgefashion.utilsPassword;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Dimension;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import koneksiDB.koneksi;

/**
 *
 * @author kitan
 */
public class Admin_Karyawan extends javax.swing.JFrame implements UpdateKaryawan, utilsPassword {

    /**
     * Creates new form editdelete_karyawan
     */
    public Admin_Karyawan(String nama) throws SQLException {
        initComponents();
        this.setTitle("KELOLA DATA KARYAWAN");
        this.ic_hidden.setVisible(false);


        SetNama(nama);
        getAllDataKaryawan();
    }
    
//    String nomerHp = "";
    public void wa(){
    String urlfb = "https://api.whatsapp.com/send/?phone="+txt_telepon.getText()+"&text&app_absent=0";
        
        if (Desktop.isDesktopSupported()){
        Desktop desktop = Desktop.getDesktop();
            try {
                desktop.browse(new URI(urlfb));
            } catch (IOException | URISyntaxException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }else {
        Runtime runtime = Runtime.getRuntime();
        try {
                runtime.exec("xdg-open " + urlfb);
            } catch (IOException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
    
    }
    private void lebar_tabelbarang(){
   
        TableColumn kolom;
        table_karyawan.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN); 
        kolom = table_karyawan.getColumnModel().getColumn(0); 
        kolom.setPreferredWidth(50);
        kolom = table_karyawan.getColumnModel().getColumn(1); 
        kolom.setPreferredWidth(50); 
        kolom = table_karyawan.getColumnModel().getColumn(2); 
        kolom.setPreferredWidth(620); 

       
    }

    public void SetNama(String user) {
        userr.setText(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_idkrywn1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_idrkywn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_namakrywn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_alamat = new javax.swing.JTextField();
        txt_telepon = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        txt_type = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_karyawan = new javax.swing.JTable();
        txt_username = new javax.swing.JTextField();
        txt_username1 = new javax.swing.JTextField();
        ic_hidden = new javax.swing.JLabel();
        ic_show = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        btn_edit1 = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        txt_idkrywn1.setBackground(new java.awt.Color(196, 196, 196));
        txt_idkrywn1.setCaretColor(new java.awt.Color(196, 196, 196));
        txt_idkrywn1.setBorder(null);
        txt_idkrywn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idkrywn1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        userr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userr.setForeground(new java.awt.Color(255, 255, 255));
        userr.setText("jLabel2");
        getContentPane().add(userr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 35, 160, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Type");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 80, -1));

        txt_idrkywn.setEditable(false);
        txt_idrkywn.setBackground(new java.awt.Color(255, 255, 255));
        txt_idrkywn.setForeground(new java.awt.Color(0, 0, 0));
        txt_idrkywn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_idrkywn.setCaretColor(new java.awt.Color(196, 196, 196));
        txt_idrkywn.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_idrkywn.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_idrkywn.setEnabled(false);
        txt_idrkywn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idrkywnActionPerformed(evt);
            }
        });
        jPanel1.add(txt_idrkywn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, 30));

        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 70, 20));

        txt_namakrywn.setBackground(new java.awt.Color(196, 196, 196));
        txt_namakrywn.setCaretColor(new java.awt.Color(196, 196, 196));
        txt_idkrywn1.setBorder(null);
        txt_namakrywn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namakrywnActionPerformed(evt);
            }
        });
        jPanel1.add(txt_namakrywn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 240, 30));

        jLabel5.setText("Nama Karyawan");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        txt_alamat.setBackground(new java.awt.Color(196, 196, 196));
        txt_alamat.setCaretColor(new java.awt.Color(196, 196, 196));
        txt_idkrywn1.setBorder(null);
        txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatActionPerformed(evt);
            }
        });
        jPanel1.add(txt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 150, 30));

        txt_telepon.setBackground(new java.awt.Color(196, 196, 196));
        txt_telepon.setCaretColor(new java.awt.Color(196, 196, 196));
        txt_idkrywn1.setBorder(null);
        txt_telepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_teleponActionPerformed(evt);
            }
        });
        jPanel1.add(txt_telepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 120, 30));

        jButton5.setBackground(new java.awt.Color(102, 153, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-back-24.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 40));

        txt_type.setBackground(new java.awt.Color(196, 196, 196));
        txt_type.setCaretColor(new java.awt.Color(196, 196, 196));
        txt_idkrywn1.setBorder(null);
        txt_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_typeActionPerformed(evt);
            }
        });
        jPanel1.add(txt_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 110, 30));

        jLabel6.setText("Alamat");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 40, -1));

        jLabel7.setText("No Telephone");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 80, -1));

        table_karyawan.setRowHeight(25);
        table_karyawan.setShowVerticalLines(false);
        table_karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_karyawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_karyawan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 770, 230));

        txt_username.setEditable(false);
        txt_username.setBackground(new java.awt.Color(196, 196, 196));
        txt_username.setText("user");
        txt_username.setCaretColor(new java.awt.Color(196, 196, 196));
        txt_idkrywn1.setBorder(null);
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        txt_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_usernameKeyTyped(evt);
            }
        });
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 240, 30));

        txt_username1.setBackground(new java.awt.Color(196, 196, 196));
        txt_username1.setCaretColor(new java.awt.Color(196, 196, 196));
        txt_idkrywn1.setBorder(null);
        txt_username1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_username1ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 240, 30));

        ic_hidden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ic_hidden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hidden_1.png"))); // NOI18N
        ic_hidden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ic_hiddenMouseClicked(evt);
            }
        });
        jPanel1.add(ic_hidden, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 50, 50));

        ic_show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ic_show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/show_1.png"))); // NOI18N
        ic_show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ic_showMouseClicked(evt);
            }
        });
        jPanel1.add(ic_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 50, 50));

        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 160, 30));

        btn_edit1.setBackground(new java.awt.Color(101, 209, 255));
        btn_edit1.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit1.setText("EDIT");
        btn_edit1.setBorder(null);
        btn_edit1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                btn_edit1InputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        btn_edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_edit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 140, 50));

        btn_hapus.setBackground(new java.awt.Color(255, 0, 0));
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setText("HAPUS");
        btn_hapus.setBorder(null);
        btn_hapus.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                btn_hapusInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 130, 50));

        jLabel8.setText("ID Karyawan");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel9.setText("User");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 40, 20));

        jButton1.setBackground(new java.awt.Color(0, 204, 51));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("WHATSAPP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 110, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 790, 460));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/adm_edithapuskaryawan.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  DefaultTableModel tdm;


    private void txt_idkrywn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idkrywn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idkrywn1ActionPerformed

    private void txt_idrkywnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idrkywnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idrkywnActionPerformed

    private void txt_namakrywnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namakrywnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namakrywnActionPerformed

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatActionPerformed

    private void txt_teleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_teleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_teleponActionPerformed

    private void txt_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_typeActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_username1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_username1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_username1ActionPerformed

    private void btn_hapusInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_btn_hapusInputMethodTextChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_hapusInputMethodTextChanged

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        hapusData();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_edit1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_btn_edit1InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit1InputMethodTextChanged


    private void btn_edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit1ActionPerformed

        editDataKaryawan();
        JOptionPane.showMessageDialog(null, "Update Data Berhasil !");


    }//GEN-LAST:event_btn_edit1ActionPerformed

    private void table_karyawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_karyawanMouseClicked
        try {
            // TODO add your handling code here:
            int getPositionOfRowtable = table_karyawan.rowAtPoint(evt.getPoint());
            String id_krywn = table_karyawan.getValueAt(getPositionOfRowtable, 1).toString();
            System.out.printf("%s%n", id_krywn);
            String query = "SELECT * FROM `karyawan` JOIN `login` ON `login`.`idkrywn` = `karyawan`.`idkrywn` WHERE `karyawan`.`idkrywn` = '"
                    + id_krywn + "'";
            System.out.println(query);
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.PreparedStatement prs = conn.prepareStatement(query);
            java.sql.ResultSet rs = prs.executeQuery();
            while (rs.next()) {
                this.txt_idrkywn.setText(rs.getString("idkrywn"));
                this.txt_namakrywn.setText(rs.getString("nama_krywn"));
                this.txt_alamat.setText(rs.getString("alamat"));
                this.txt_telepon.setText(rs.getString("no_telp"));
                this.txt_type.setText(rs.getString("type"));
                this.txt_username.setText(rs.getString("username"));
                this.txt_password.setText(rs.getString("password"));

            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin_Karyawan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_table_karyawanMouseClicked

    private void txt_usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usernameKeyTyped
        // TODO add your handling code here:
   
    }//GEN-LAST:event_txt_usernameKeyTyped

    private void ic_showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ic_showMouseClicked
        // TODO add your handling code here:
        this.showPassword();

    }//GEN-LAST:event_ic_showMouseClicked

    private void ic_hiddenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ic_hiddenMouseClicked
        // TODO add your handling code here:
        this.hiddenPassword();


    }//GEN-LAST:event_ic_hiddenMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Admin_Fitur(userr.getText()).setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        wa();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            try {
                UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
            } catch (Exception e) {
                e.printStackTrace();
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Admin_Karyawan(userr.getText()).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Admin_Karyawan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit1;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JLabel ic_hidden;
    private javax.swing.JLabel ic_show;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_karyawan;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_idkrywn1;
    private javax.swing.JTextField txt_idrkywn;
    private javax.swing.JTextField txt_namakrywn;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_telepon;
    private javax.swing.JTextField txt_type;
    private javax.swing.JTextField txt_username;
    private javax.swing.JTextField txt_username1;
    public static final javax.swing.JLabel userr = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables

    @Override
    public void getAllDataKaryawan() {
        try {
            String queryGet = "SELECT * FROM `login` JOIN `karyawan` ON `login`.`idkrywn` = `karyawan`.`idkrywn`";
            tdm = new DefaultTableModel();
            tdm.addColumn("no");
            tdm.addColumn("id");
            tdm.addColumn("nama karyawan");
            table_karyawan.getTableHeader().setBackground(new Color(102,153,255));
        table_karyawan.getTableHeader().setForeground(Color.WHITE);
        table_karyawan.getTableHeader().setPreferredSize(new Dimension(20,30));
            java.sql.Connection con = (Connection) koneksi.configDB();
            java.sql.PreparedStatement prs = con.prepareStatement(queryGet);
            java.sql.ResultSet rs = prs.executeQuery();

            int no = 1;
            while (rs.next()) {
                tdm.addRow(new Object[]{
                    no++,
                     rs.getString("idkrywn"),
                    rs.getString("nama_krywn")
                });
            }

            this.table_karyawan.setModel(tdm);
            lebar_tabelbarang();
        } catch (SQLException ex) {
            Logger.getLogger(Admin_Karyawan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void hapusData() {
        try {
            String queryDeleteLogin = "DELETE FROM `login` WHERE `idkrywn` = '" + this.txt_idrkywn.getText() + "'";
            System.out.println(queryDeleteLogin);

            java.sql.Connection connLogin = (Connection) koneksi.configDB();
            java.sql.Statement stmLogin = connLogin.createStatement();
            stmLogin.execute(queryDeleteLogin);

//            String queryDeleteKaryawan = "DELETE FROM `karyawan` WHERE `idkrywn` = '" + this.txt_idrkywn.getText() + "'";
//            System.out.println(queryDeleteLogin);
//
//            java.sql.Connection connKaryawan = (Connection) koneksi.configDB();
//            java.sql.Statement stmKaryawan = connKaryawan.createStatement();
//            stmKaryawan.execute(queryDeleteKaryawan);
            //resetField
            //loaddata

          

            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus ");
            getAllDataKaryawan();
        } catch (SQLException ex) {
            Logger.getLogger(Admin_Karyawan.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    @Override
    public void editDataKaryawan() {
        try {
            String id_krywn = this.txt_idrkywn.getText();
            String namakrywn = this.txt_namakrywn.getText();
            String alamat = this.txt_alamat.getText();
            String no_telpon = this.txt_telepon.getText();
            String type = this.txt_type.getText();
            String username = this.txt_username.getText();
            String password = new String(this.txt_password.getPassword());

            System.out.println(password);
            String queryEditLogin = "UPDATE `login` SET `username` = '" + username + "' , `password` = '"
                    + password + "' WHERE `idkrywn` = '" + id_krywn + "';";
            System.out.println(queryEditLogin);
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            stm.executeUpdate(queryEditLogin);
            String queryEditKaryawan = "UPDATE `karyawan` SET `nama_krywn` = '"
                    + namakrywn + "' , `alamat` = '" + alamat + "', `no_telp` = '" + no_telpon
                    + "',`type` = '" + type + "' WHERE `idkrywn` = '" + id_krywn + "';";
            System.out.println(queryEditKaryawan);
            java.sql.Connection connKaryawan = (Connection) koneksi.configDB();
            java.sql.Statement stmd = connKaryawan.createStatement();
            stmd.execute(queryEditKaryawan);
            getAllDataKaryawan();
        } catch (SQLException ex) {
            Logger.getLogger(Admin_Karyawan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void showPassword() {
        this.ic_show.setVisible(false);
        this.ic_show.setEnabled(false);
        this.ic_hidden.setVisible(true);
        this.ic_hidden.setEnabled(true);
        this.txt_password.setEchoChar(((char) 0));
    }

    @Override
    public void hiddenPassword() {
        this.ic_hidden.setVisible(false);
        this.ic_hidden.setEnabled(false);
        this.ic_show.setVisible(true);
        this.ic_show.setEnabled(true);
        this.txt_password.setEchoChar('*');

    }
}
