/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import koneksiDB.koneksi;
/**
 *
 * @author kitan
 */
public class Admin_DaftarSuplier extends javax.swing.JFrame {

    /**
     * Creates new form regist_supplier
     */
    public Admin_DaftarSuplier(String nama) {
        initComponents();
        this.setTitle("DAFTAR SUPPLIER");
     
        SetNama(nama);
        autoIdBrg();
        txt_idsupplier.setEditable(false);
    }
      public void SetNama(String user){
        userr.setText(user);
    }
      
     public void RisetField(){
     txt_namasupplier.setText("");
     txt_alamat.setText("");
     txt_notelpsupplier.setText("");
     
     }
     private void autoIdBrg(){
      
       String autoNumber = "SELECT * FROM supplier ORDER BY id_supplier DESC";
   
   try{
       java.sql.Connection conn = (Connection) koneksi.configDB();
       java.sql.PreparedStatement stm = conn.prepareStatement(autoNumber);
       java.sql.ResultSet res = stm.executeQuery(autoNumber);
       
       if(res.next()){
           String id = res.getString(1).substring(2);
           String TR = ""+(Integer.parseInt(id)+1);
           String nol = "";
           
           if(TR.length()==1){
            nol = "0";
            }
            else if(TR.length()==2){
            nol = "";
            }
           txt_idsupplier.setText("SP"+nol+TR);
       } else {
           txt_idsupplier.setText("SP01");
       }
       
       
   }catch(Exception e){
       e.getMessage();
   }
   
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_alamat = new javax.swing.JTextField();
        txt_idsupplier = new javax.swing.JTextField();
        txt_namasupplier = new javax.swing.JTextField();
        txt_notelpsupplier = new javax.swing.JTextField();
        btn_register = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_alamat.setBackground(new java.awt.Color(196, 196, 196));
        txt_alamat.setForeground(new java.awt.Color(0, 0, 0));
        txt_alamat.setCaretColor(new java.awt.Color(196, 196, 196));
        txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatActionPerformed(evt);
            }
        });
        getContentPane().add(txt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 240, 30));

        txt_idsupplier.setBackground(new java.awt.Color(196, 196, 196));
        txt_idsupplier.setForeground(new java.awt.Color(0, 0, 0));
        txt_idsupplier.setCaretColor(new java.awt.Color(196, 196, 196));
        txt_idsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idsupplierActionPerformed(evt);
            }
        });
        txt_idsupplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_idsupplierKeyTyped(evt);
            }
        });
        getContentPane().add(txt_idsupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 240, 30));

        txt_namasupplier.setBackground(new java.awt.Color(196, 196, 196));
        txt_namasupplier.setForeground(new java.awt.Color(0, 0, 0));
        txt_namasupplier.setCaretColor(new java.awt.Color(196, 196, 196));
        txt_namasupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namasupplierActionPerformed(evt);
            }
        });
        getContentPane().add(txt_namasupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 240, 30));

        txt_notelpsupplier.setBackground(new java.awt.Color(196, 196, 196));
        txt_notelpsupplier.setForeground(new java.awt.Color(0, 0, 0));
        txt_notelpsupplier.setCaretColor(new java.awt.Color(196, 196, 196));
        txt_notelpsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_notelpsupplierActionPerformed(evt);
            }
        });
        getContentPane().add(txt_notelpsupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 240, 30));

        btn_register.setBackground(new java.awt.Color(255, 101, 132));
        btn_register.setForeground(new java.awt.Color(255, 255, 255));
        btn_register.setText("REGISTER");
        btn_register.setBorder(null);
        btn_register.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                btn_registerInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 280, 60));

        jButton5.setBackground(new java.awt.Color(102, 153, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-back-24.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 50, 40));

        userr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userr.setForeground(new java.awt.Color(255, 255, 255));
        userr.setText("jLabel2");
        getContentPane().add(userr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 35, 160, 30));

        jLabel4.setText("* Ganti 0 awal nomer dengan 62");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 170, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/adm_registsupplier.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatActionPerformed

    private void txt_idsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idsupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idsupplierActionPerformed

    private void txt_namasupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namasupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namasupplierActionPerformed

    private void txt_notelpsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_notelpsupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_notelpsupplierActionPerformed

    private void btn_registerInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_btn_registerInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_registerInputMethodTextChanged

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        
        try {
            String queryRegister = "INSERT INTO `supplier` VALUES ('" + this.txt_idsupplier.getText() + "','"
                    + this.txt_namasupplier.getText() + "','" + this.txt_alamat.getText() +"','" 
                    + this.txt_notelpsupplier.getText() + "');";
            System.out.printf("%s%n",queryRegister);
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            stm.execute(queryRegister);
            JOptionPane.showMessageDialog(null,"Register Supplier Telah Berhasil !");
            RisetField();
        } catch (SQLException ex) {
            Logger.getLogger(Admin_DaftarSuplier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_registerActionPerformed

    private void txt_idsupplierKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idsupplierKeyTyped
        // TODO add your handling code here:
   
    }//GEN-LAST:event_txt_idsupplierKeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Admin_Fitur(userr.getText()).setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**  
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            try {
            UIManager.setLookAndFeel( UIManager.getCrossPlatformLookAndFeelClassName() );
         } catch (Exception e) {
            e.printStackTrace();
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_DaftarSuplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_DaftarSuplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_DaftarSuplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_DaftarSuplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_DaftarSuplier(userr.getText()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_register;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_idsupplier;
    private javax.swing.JTextField txt_namasupplier;
    private javax.swing.JTextField txt_notelpsupplier;
    public static final javax.swing.JLabel userr = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
}
